
URL="https://www.saucedemo.com/"
usernameID="user-name"
loginButtonID="login-button"
passwordID="password"
addToCartID="add-to-cart-sauce-labs-backpack"
shoppingButtonID="shopping_cart_container"
checkoutButtonID="checkout"
firstNameID="first-name"
lastNameID="last-name"
zipCodeID="postal-code"
continueButtonID="continue"
finishButtonID="finish"
menuButtonID="react-burger-menu-btn"
logoutButtonID="logout_sidebar_link"
sortByButtonCS="product_sort_container"
lowToHighButtonXpath="//*[@id='header_container']/div[2]/div/span/select/option[3]"